spring.application.name=spring

# 1. Connection (Port 5432 matches your 'docker ps' output)
spring.datasource.url=jdbc:postgresql://localhost:54325/testdb
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate (The "Magic" that creates tables for you)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect